[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/api/*"
  to = "https://nexprep-qljw.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
